logging:
  level:
    ROOT: INFO
    pl.bkwapisz.taskprocessor: DEBUG

spring:
  jackson:
    default-property-inclusion: NON_NULL
    serialization.indent_output: true
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost/test}
  rabbitmq:
    host: ${RABBITMQ_HOSTNAME:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1s
          max-attempts: 3
          multiplier: 3

taskProcessor:
  cache:
    defaultCacheDurationMs: 500
  rabbitmq:
    taskProcessorEnabled: true
    tasksQueueName: "dev-tasks"
    tasksQueueListenerConcurrency: "8-8"