logging:
  level:
    ROOT: INFO

spring:
  jackson:
    default-property-inclusion: NON_NULL
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost/test}
  rabbitmq:
    host: ${RABBITMQ_HOSTNAME:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}